
services:
  web:
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 8000
    #volumes:
     # - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - MODULE_NAME=app.main
      - VARIABLE_NAME=app
      - WORKERS_PER_CORE=1
      - WEB_CONCURRENCY=1
