name: Test Build Publish Docker

on:
  push:

jobs:

  docker_build:
    name: Docker Build
    uses: andrejvysny/workflows/.github/workflows/docker_build_push_ghcr.yaml@main
    with:
      context: .
      tags: ghcr.io/mopped-hackers/backend-hk24
      dockerfile: ./.docker/Dockerfile
    secrets:
      access_token: ${{ secrets.GITHUB_TOKEN }}